### ISSUE TITLE
not compatible to latest dev

### ISSUE THREAD

**Issue by andweber** [bacardi55/kalliope-list-available-orders#2]
neuron is no longer compatible with dev (https://github.com/kalliope-project/kalliope/commit/e0cc4fd90c9f96057a8768adbbccca4ffb39707c)

It seems models/Order.py was renamed to "signal" with:

https://github.com/kalliope-project/kalliope/pull/321

**Comment by bacardi55** [comment]
Thanks, it's finally fixed now.
